### ISSUE TITLE
paquete duplicado

### ISSUE THREAD

**Issue by ftoledo** [HuayraLinux/repo-frontend#10]
En la vista del paquete, donde se muestran los links de descarga, aparecen duplicados ya que es el mismo archivo.

ejemplo:
http://repo-frontend.surge.sh/#/packages/zonda/rtl-8723-firmware

captura:
![repofrontend](https://cloud.githubusercontent.com/assets/95441/19271301/7f0e194c-8f9a-11e6-91df-ff6274a93f7d.png)

**Comment by iglosiggio** [comment]
Era un bug de [repo-backend](https://github.com/HuayraLinux/repo-backend), lo fixié [recién](https://github.com/HuayraLinux/repo-backend/compare/863918e...1a2fdab)
