### ISSUE TITLE
arquitecturas duplicadas en el listado de paquetes por distro

### ISSUE THREAD

**Issue by ftoledo** [HuayraLinux/repo-frontend#12]
![repofrontend](https://cloud.githubusercontent.com/assets/95441/19271901/f7316486-8f9c-11e6-8f56-97e8c1d3f5a3.png)

**Comment by iglosiggio** [comment]
Era un bug de [repo-backend](https://github.com/HuayraLinux/repo-backend), lo fixié [recién](https://github.com/HuayraLinux/repo-backend/compare/863918e...1a2fdab)

**Comment by ftoledo** [comment]
░░░░░░░░░░░░▄▄
░░░░░░░░░░░█░░█
░░░░░░░░░░░█░░█
░░░░░░░░░░█░░░█
░░░░░░░░░█░░░░█
███████▄▄█░░░░░██████▄
▓▓▓▓▓▓█░░░░░░░░░░░░░░█
▓▓▓▓▓▓█░░░░░░░░░░░░░░█
▓▓▓▓▓▓█░░░░░░░░░░░░░░█
▓▓▓▓▓▓█░░░░░░░░░░░░░░█
▓▓▓▓▓▓█░░░░░░░░░░░░░░█
▓▓▓▓▓▓█████░░░░░░░░░█
██████▀░░░░▀▀██████▀
