### ISSUE TITLE
Agregar la funcionalidad de búsqueda de paquetes

### ISSUE THREAD

**Issue by ftoledo** [HuayraLinux/repo-frontend#14]
Se tiene que agregar un botón de búsqueda que figure desde la pantalla de inicio. (puede ser algo persistente tambien entre las diferentes vistas)

Al menos se tiene que poder buscar por nombre de paquete y en las descripciones. (opcionalmente se podría agregar un filtro que se por una distro específica o todas)

Como resultado, se tiene que mostrar el listado de paquetes que coincidan con esos criterios.
(deberíamos mostrar al menos: nombre del paquete, versión, descripcion corta, distro, arquitectura, algo similar al listado de _paquetes por distro_) 

Se tiene que poder hacer un click en el nombre del paquete e ir la pagina del mismo.
Tener en cuenta si el paquete es un binario o un source para formar el link.

El backend debe guardar algun contador de la búsqueda para sacar una estadística a futuro, de por ejemplo "paquetes mas buscados".

**Comment by iglosiggio** [comment]
Finalmente tenemos una implementación básica de la búsqueda!

(Cierro por ahora)
Source: http://devel.huayra.conectarigualdad.gob.ar/
