### ISSUE TITLE
agregar un hover sobre las filas

### ISSUE THREAD

**Issue by ftoledo** [HuayraLinux/repo-frontend#17]
Cuando se listan muchas versiones del paquete, es mas facil selecionar uno si hay un hover del mouse en toda la fila que lo resalte
![screenshot-2017-11-25 repofrontend](https://user-images.githubusercontent.com/95441/33235008-ef61b250-d20e-11e7-9bc2-d2f95f856942.png)

**Comment by hugoruscitti** [comment]
Ví que semantic-ui ya trae una clase para esto, así que simplemente se la asigné a todas las tablas: https://semantic-ui.com/collections/table.html
